language: node_js
node_js: 9.8.0
sudo: required
services:
- docker
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y jq
- npm install firebase-tools --global
script:
- make all REBLOG=docker\ run\ -v\ $(pwd):/context\ -u\ `id -u $USER`:`id -g $USER`\
  natewilkins/reblog
notifications:
  slack:
    secure: gEoJW+6i0U8lnHkxKFF/xN9eKiawNgDwAfjlBW408TlJWhXscF+/rA+6Jc/zLVeyR5FGMcvnj1JXeyYrMe085Lss2iI+u8j2eQfN99UsGuKixK6louUqy5fGWjTtr1gjEDg/MlXjybygKEprGGqg5Mr8d7eCGBlMO0WY7A/isS0dmZMZ81DfaakNtaTocHsl4w/Sb+uZNXk6HRLhrsvpCZWKn3C+WJ43UJkxj+MK4HWz/avXtNoEXeuCLH8GOSr1DJATjFZWUURshcbSbLwDr0niVAuyZfkXxeyfPbhs9ns+sCGqTsBCQCGyyai3zqLNakVA7qPsG8nRn7GHRiS0EV3QIEQ/egzIHhk4xbsAkrTj01jo/KRRsVqiQiBFygJLGE96a52GA+pFpizvZgCk5vK4dwTMu9vG/6jjdeC9OvDVwGtp0FlHY2AuPQTtObL3Pktqg53w0C4tXsvyBy+5/1QVGRTM1pwFTYYVwg7MT3cmaTdVV/sZKMh67gFe/vWyMz6BIXOrPDcpEDnVgFEObMB2mK4sfQ8/Jhz2Fg9isVwTvIC4i4+CXp4YrPh4nOOk+UvXzo+bwJqwfNvHmL03wqo9jyxs61bKwhkayINchCsRGlY6ZRE0eajx8EUzkyq00kVDvO6JtXoQnH8uIDX4eZJi6V/KM+9RgsmwWYEr+9o=
